version: '2'

services:
  devfaq_db:
    image: postgres:11-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'test'
      POSTGRES_DB: 'test'
      POSTGRES_PASSWORD: 'test'
