version: '2'

services:
  typeofweb:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'test'
      POSTGRES_DB: 'test'
      POSTGRES_PASSWORD: 'test'
